ansible/roles/raspi-config/tasks/main.yml, packer/README.md
=> 40 ansible ssh not started

ansible/roles/ps4-controller/tasks/main.yml, ansible/roles/ps4-controller/templates/ds4drv.conf.j2, ansible/roles/ps4-controller/templates/picture.sh.j2
- Fixes #55 . 
I have introduce a command to allow a user to take a picture with ps4 controller for test the resolution or verify that the camera running
**The shortcut is : PS + Triangle + L2 + R2**
**ALL TESTS PASSED**
=> Resolves #55 :  [Ansible] Shortcut to take full resolution picture (check camera quality)

doc/controller.md
PS4 Controller doc associating the shortcuts and their description
=> fixes #76 Controller documentation

.github/workflows/raspberrypi-image-build-needed.yml
Triger post comment on PR Thread for pull_request_target
=> :bug: Fixes #86, trigger post comment

.github/workflows/raspberrypi-image-build-needed.yml
Concurrency based on branch names for PR.
=> :bug: [CI] Fixes #92, concurrency for github action

.github/workflows/raspberrypi-image-build-needed.yml
:bug: [CI] Fixes #96, image file path errors
=> :bug: [CI] Fixes #96, image file path errors

backend/donkeycarmanager/crud/cars.py, backend/donkeycarmanager/crud/driving_waiting_queue.py, backend/donkeycarmanager/crud/laptimers.py, backend/donkeycarmanager/emitters/cars.py, backend/donkeycarmanager/emitters/laptimers.py, backend/donkeycarmanager/routers/cars.py, backend/donkeycarmanager/routers/laptimers.py, backend/donkeycarmanager/schemas.py, backend/socketioTestPage.html, doc/donkeycarManager/event-spec-asyncio.yaml
Fixes #107, add cars events and laptimers events.
=> :sparkles: [Backend] Fixes #107, add cars events and laptimers events.

3dDesigns/circuit-border/SupportBarriereDonkeyCar.scad, 3dDesigns/circuit-border/SupportBarriereDonkeyCar.stl
3D parts for supports used to raise the circuit border
=> [3dParts] :sparkles: Adding support for circuit border

ansible/config/bluecar/myconfig.py, ansible/config/dababycar/myconfig.py, ansible/config/monkecar/myconfig.py, ansible/config/pimpcar/myconfig.py, ansible/roles/raspi-config/tasks/main.yml
=> 🗿 Reduce base car speed and add fix problem over ssh on certain terminals

ansible/roles/IR-lap-timer/tasks/main.yml
Fixes #133 
- ✨ add IR module activation of rc.local in the ansible recipe
=> add IR module activation in rc.local

ansible/roles/mycar/files/custom/manager/car_manager_api_service.py, ansible/roles/mycar/files/custom/manager/jobs/job_drive.py, ansible/roles/mycar/files/custom/manager/race_service.py, ansible/roles/mycar/files/custom/manager/schemas.py, backend/donkeycarmanager/app.py, backend/donkeycarmanager/crud/players.py, backend/donkeycarmanager/crud/workers.py, backend/donkeycarmanager/dependencies.py, backend/donkeycarmanager/emitters/workers.py, backend/donkeycarmanager/routers/players.py, backend/donkeycarmanager/routers/workers.py, backend/donkeycarmanager/schemas.py, backend/donkeycarmanager/services/async_job_scheduler.py, backend/donkeycarmanager/worker_heartbeat_manager.py
- Fixing 500, db connexion lifecycle
- First boot car creation not returned by service causing job handeling issues after
=> Front first tests back issues

backend/donkeycarmanager/app.py, backend/donkeycarmanager/dependencies.py, backend/donkeycarmanager/worker_heartbeat_manager.py
=> :bug: [Backend] Fixes #162 Heartbeat manager wrong dependency injection

ansible/roles/mycar/files/custom/manager/jobs/job_drive.py, ansible/roles/mycar/files/custom/manager/jobs/job_record.py, backend/.gitignore
=> Use controller icons in screen_msg

.github/workflows/raspberrypi-image-build-needed.yml
=> Use Google Cloud Storage in CI/CD

ansible/roles/mycar/files/custom/manager/car_manager_api_service.py, ansible/roles/mycar/files/custom/manager/jobs/job_drive.py, ansible/roles/mycar/files/custom/manager/race_service.py, ansible/roles/mycar/files/custom/manager/schemas.py, backend/donkeycarmanager/crud/races.py, backend/donkeycarmanager/emitters/races.py, backend/donkeycarmanager/models.py, backend/donkeycarmanager/routers/races.py, backend/donkeycarmanager/schemas.py, backend/socketioTestPage.html, doc/donkeycarManager/event-spec-asyncio.yaml
Add end_datetime into races.
As there are no events on races I'm not sure it will be useful ? Should I add races (updates) events @viandoxdev ?
=> :sparkles: [Car + Back] End races

ansible/roles/mycar/files/custom/manager/car_manager.py, ansible/roles/mycar/files/custom/manager/schemas.py, ansible/roles/mycar/files/manage.py, ansible/roles/mycar/files/my_joystick.py, backend/donkeycarmanager/models.py, backend/donkeycarmanager/schemas.py
Adds the capacity for the user to invert controls (left/right) and expose in the api the state of the controls (inverted or not and throttle scale).
=> [Car / Backend] better controls

backend/donkeycarmanager/database.py
Fixes #219 , multiply by 3 the size of the pool, should be enough unfortunately I wasn't able to reproduce the error.
=> :wrench: [Backend] Fixes #219, increase database pool and overflow

ansible/roles/mycar/files/custom/car/helpers/os.py, ansible/roles/mycar/files/custom/car/parts/car_manager_part.py, ansible/roles/mycar/files/custom/car/services/car_job_service.py, ansible/roles/mycar/files/custom/car/services/jobs/job.py, ansible/roles/mycar/files/custom/car/services/jobs/job_ai_assisted.py, ansible/roles/mycar/files/custom/car/services/jobs/job_drive.py, ansible/roles/mycar/files/custom/car/services/jobs/job_record.py, ansible/roles/mycar/files/manage.py, ansible/roles/mycar/files/myconfig.py, ansible/roles/mycar/files/requirements.txt, dkmanager_trainner/dkmanager_trainer/services/jobs/job_train.py, dkmanager_worker/dkmanager_worker/services/job_service.py
=> :construction: [Car] AI Assisted job first version

donkeycarManagerFront/src/components/clientView.vue
=> [Front] enforce order for cars

ansible/roles/donkeycar/tasks/main.yml
Downgrade setuptools in an attempt to fix the pipeline
=> Attempt to fix pipeline

ansible/roles/mycar/files/my_joystick.py
Fixes #238 
✨ Add a easy drive mode
=> Resolves #238 : Add a easy drive mode

donkeycarManagerFront/src/components/carInfo.vue, donkeycarManagerFront/src/components/runningJobCard.vue
=> Resolves #246 : Add color

backend/docker-compose.yml, dkmanager_trainner/README.md, dkmanager_trainner/dkmanager_trainer/services/ai_trainer_worker_service.py, dkmanager_worker/dkmanager_worker/services/manager_api_service.py
Fixes #263 multiple AI trainner
=> Fixes #263 :bug: [AI] Multi trainner

donkeycarManagerFront/src/js/utils.js
=> [Front] Fix NaNs appearing in frontend

donkeycarManagerFront/src/components/runningJobCard.vue
Fixes #283 
- ✨ Fix broken button
=> [ Front ] Fixe button

ansible/config/dababycar/myconfig.py, dkmanager_trainner/dkmanager_trainer/controllers/cli.py
=> [Ansible] Calibration of dababycar improved, fixes #284
